/* ECE 420 Lab #1
 * By: Divyank Katira
 * ID: 1342635
 * 
 * Usage: gcc matmul.c -o matmul -lpthread -lm
 *
 * Matrix generation functions from matrixgen.c from eclass
 */
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "timer.h"

#define BD 10 
#define MAXSIZE 8   // Size by SIZE matrices
int num_thrd;   // number of threads
int n;	//Size
 
int A[MAXSIZE][MAXSIZE], B[MAXSIZE][MAXSIZE], C[MAXSIZE][MAXSIZE];

void* multiply(void* rank) 
{
	int i,j,m;
	int root_p = sqrt(num_thrd);
	/* Compute Block Size */
	int k = (int) rank;
	int x = k / root_p;
	int y = k % root_p;
	/* Compute output block */
	for (i = (n/root_p) * x; (i <= (n/root_p) * (x+1) -1); i++) {
		for (j = (n/root_p) * y; (j <= (n/root_p) * (y+1) -1); j++) {
			C[i][j] = 0;
      		for ( m = 0; m < n; m++)
 				C[i][j] += A[i][m]*B[m][j];
 		}			
	}	
	return 0;
}

void print_matrix(int m[MAXSIZE][MAXSIZE])
{
  int i, j;
  for (i = 0; i < n; i++) {
    printf("\n\t| ");
    for (j = 0; j < n; j++)
      printf("%2d ", m[i][j]);
    printf("|");
  }
}

int Lab1_loadinput(int *A, int *B, int *n)
{
	/*
		The function to load the data generated by matrixgen.c

		The input are the pointer to the two matrices and the pointer 
		to the variable storing the matrix size.
		MAKE SURE that you declared two array with the exact SAME 
		size of the matrix you generated with matrixgen.c
		
		Note that the input is of type int *. If you declared arrays 
		with type int *[], you need to CONVERT to type int*. For example
		if you declared some array like
		int A_[16][16],B_[16][16];
		int n_;
		To call the function, you can use
		Lab1_loadinput(*A_, *B_, &n_);

		Also note that the third argument is a pointer!
	*/

        FILE* ip;
        int i,j;
        if ((ip=fopen("data_input","r"))==NULL)
        {
                printf("error opening the input data.\n");
                return 1;
        }
        fscanf(ip,"%d\n",n);
        for (i=0;i<*n;i++)
                for (j=0;j<*n;j++)
                        fscanf(ip,"%d\t",A+*n*i+j);     
        for (i=0;i<*n;i++)
                for (j=0;j<*n;j++)
                        fscanf(ip,"%d\t",B+*n*i+j);
	fclose(ip);     
        return 0;
}

int Lab1_saveoutput(int *C, int *n)
{	
	/*
		The function to save the result matrix to a file.

		The input are the pointer to the result matrix and the pointer 
		to the variable storing the matrix size.
		MAKE SURE that you declared the result array with the exact SAME 
		size of the matrix you generated with matrixgen.c
		
		Note that the input is of type int *. If you declared arrays 
		with type int *[], you need to CONVERT to type int*. For example
		if you declared some array like
		int C_[16][16];
		int n_;
		To call the function, you can use
		Lab1_loadinput(*C_, &n_);

		Also note that the second argument is a pointer!

		The output will be stored at the file 
		./data_output
	*/
	FILE* op;
	int i,j;
	if ((op=fopen("data_output","w"))==NULL)
	{
		printf("Error opening the output file.\n");
		return 1;
	}
	fprintf(op,"%d\n\n",*n);
	for (i=0;i<*n;i++)
	{
		for (j=0;j<*n;j++)
			fprintf(op,"%d\t",C[*n*i+j]);
		fprintf(op,"\n");
	}
	fclose(op);
	return 0;	
}



int main(int argc, char* argv[]) 
{	
	double start, end;
	int i,j;
	pthread_t* thread;  // pointer to a set of pthreads
	//Argument validation
	if (argc!=3)
  	{
    	printf("Usage: %s number_of_threads matrix_size\n",argv[0]);
    	exit(-1);
  	}
  	num_thrd = atoi(argv[1]);
  	n = atoi(argv[2]);
  	if ( n > MAXSIZE || n%num_thrd != 0)
  	{
  		printf("MAX SIZE = %d, SIZE must be divisible by num_thrd\n",MAXSIZE);
    	exit(-1);	
  	}
  	//Generate matrices
	/*
  	for (i=0;i<n;i++)
	{	
		for (j=0;j<n;j++)
		{
			A[i][j]=rand()%(2*BD)-BD+1;
			B[i][j]=rand()%(2*BD)-BD+1;
		}
	}
	*/
	Lab1_loadinput(*A, *B, &n);
	thread = (pthread_t*) malloc(num_thrd*sizeof(pthread_t));
	GET_TIME(start);
	for (i = 0; i <= num_thrd-1; i++)
	{
    		if (pthread_create (&thread[i], NULL, multiply, (void*)i) != 0 )
    		{
      			perror("Can't create thread");
      			free(thread);
      			exit(-1);
    		}
  	}
  	for (i = 0; i <= num_thrd -1 ; i++)
 		pthread_join (thread[i], NULL);
 	GET_TIME(end);
  	printf("\n\n");
  	print_matrix(A);
  	printf("\n\n\t       * \n");
  	print_matrix(B);
  	printf("\n\n\t       = \n");
  	print_matrix(C);
  	printf("\n\n");
	printf("Computation Time : %F \n", (end - start));
 	Lab1_saveoutput(*C, &n);
	free(thread);
 
 	return 1;
}
